audio:
  mp3_bitrate: "320k"
  normalize_peak_db: -1

tracks:
  per_track:

    "01 BASS":
      compression:
        threshold_db: -13
        ratio: 3
        attack_ms: 1
        release_ms: 50
        knee_db: 2
      dynaudnorm:
        peak: 0.95
        max_gain: 3
        frame_length_ms: 500

    "02 GUIT MIX":
      gain_db: -8

    "04 KEYS MIX":
      gain_db: -14

    "09 BACKING VOC":
      compression:
        threshold_db: -14
        ratio: 5.2
        attack_ms: 1
        release_ms: 60
        knee_db: 5.5
      gain_db: -4
      dynaudnorm:

    "10 LEAD VOCAL":
      compression:
        threshold_db: -14
        ratio: 5.2
        attack_ms: 1
        release_ms: 60
        knee_db: 5.5
      gain_db: 2
      dynaudnorm:

    "11 DR KICK":
      compression:
        threshold_db: -14
        ratio: 4
        attack_ms: 30
        release_ms: 120
        knee_db: 0.5
      dynaudnorm:

    "12 DR HH SD":
      compression:
        threshold_db: -14
        ratio: 4
        attack_ms: 0.2
        release_ms: 210
        knee_db: 18
      dynaudnorm:

  mixes:

    - output: "02 GUIT MIX"
      sources:
        - file: "02 GUIT DI"
          pan: 10
        - file: "03 GUIT MIC"
          pan: -5
          gain_db: -15
    - output: "04 KEYS MIX"
      sources:
        - file: "04 KEYS L"
          pan: -100
        - file: "05 KEYS R"
          pan: 100
    - output: "11 DRUMS MIX"
      sources:
        - file: "11 DR KICK"
          pan: 20
        - file: "12 DR HH SD"
          pan: -20

  exclude:

    - "20 AMBIANCE"

blabla_mix:
  pans:
    "01 BASS": 0
    "02 GUIT MIX": 0
    "04 KEYS MIX": 0
    "09 BACKING VOC": 0
    "10 LEAD VOCAL": 0
    "11 DRUMS MIX": 0
